# this is a copy of the original application.yml
# change the placeholder to the original value
# ask the developer for the key

spring:
  # database
  datasource:
    driver-class-name: JDBC Driver
    url: path
    username: username
    password: password

  # 404
  mvc:
    throw-exception-if-no-handler-found: boolean

jwt:
  key: secret-key